name: Policy Comparison

on:
  schedule:
    # Run at 2 AM UTC every Monday
    - cron: "0 2 * * 1"
  workflow_dispatch:
    inputs:
      max_policies:
        description: "Maximum number of policies to compare"
        required: true
        default: "10"
        type: number

jobs:
  compare-policies:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Chrome
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get -y install google-chrome-stable

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Generate test data
        run: |
          python scripts/test_data_generator.py --output data/policy_comparison_data.xlsx --count 10

      - name: Run comparison
        run: |
          max_policies=${{ github.event.inputs.max_policies || 10 }}
          python scripts/compare_urls.py --config data/policy_comparison_data.xlsx --output results/policy_comparisons.xlsx --headless --max $max_policies

      - name: Upload results
        uses: actions/upload-artifact@v4.6.2
        with:
          name: policy-comparison-results
          path: results/policy_comparisons.xlsx

      - name: Commit and push if there are changes
        run: |
          mkdir -p results
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
          # Add both results and updated data files
          git add results/ data/policy_comparison_data.xlsx
          # Check if there are changes and commit only if needed
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update policy comparison results" && git push)
